### PR TITLE
Remove excessive HTML from the markdown

### PR DESCRIPTION
**Pull request by RobLoach**
* Removes the center aligned image/badges
* Replicates more of what's used in https://github.com/then/promise

[Preview](https://github.com/jstransformers/jstransformer/blob/no-center/README.md)

RE: #21

### CODE REVIEW

**Comment by tunnckoCore** [comment]
mmnope. maybe better is to be after the heading, floated to the right. i thought that was the inital idea.

**Comment by tunnckoCore** [comment]
like PostCSS's
- https://github.com/postcss/postcss-simple-vars
- https://github.com/postcss/postcss

**Comment by RobLoach** [comment]
Matches postcss now.

**Comment by TimothyGu** [comment]
Ack. I still prefer the original styles but the result isn't ugly so meh.

**Comment by tunnckoCore** [comment]
@RobLoach no looks great!

**Comment by ForbesLindesay** [comment]
Personally I prefer the centred look, but if everyone else prefers @RobLoach's version then I don't mind.

**Comment by RobLoach** [comment]
I prefer the centered look too. I just [don't like the look of the Markdown](https://raw.githubusercontent.com/jstransformers/jstransformer/master/README.md), or lack there of. I vote we leave it in there.

**Comment by tunnckoCore** [comment]
:+1:

**Comment by tunnckoCore** [comment]
:+1:  So we can close and stay with the centered. :) It looks more official and cool. Each Transformer would be with the small logo in right :)

**Pull request closed without merging**
