### PR TITLE
Add logo by @stoeffel

### PR DESCRIPTION
**Pull request by RobLoach**
From https://github.com/jstransformers/meta/issues/1#issuecomment-89755861 . This thing is awesome. Thoughts on the markdown?

Preview: https://github.com/RobLoach/jstransformer/blob/logo/README.md

### CODE REVIEW

**Comment by stoeffel** [comment]
:rainbow:

**Comment by tunnckoCore** [comment]
:+1: looks awesome, except this lines on top of it, because the headings, but..

**Comment by tunnckoCore** [comment]
what about to add it in every repository?

**Comment by stoeffel** [comment]
> what about to add it in every repository?

... and you can add it as the organisation logo.

I would make it a little smaller in the readme so it fits in one paragraph like f.e. https://github.com/ramda/ramda#why-ramda

**Comment by tunnckoCore** [comment]
@stoeffel yea, it would be great :) will wait then, thanks for the work.

**Comment by stoeffel** [comment]
@tunnckoCore np :smile:

**Comment by RobLoach** [comment]
150px, and badges on top?

jstransformers

**Comment by tunnckoCore** [comment]
@RobLoach yea. :+1: I think my flow about badges and package name is better because if the name of the repository is too long it pull badges.

see this https://github.com/tunnckoCore/jstransformer-handlebars

**Comment by stoeffel** [comment]
:smile: I can give you the svg. So you can scale

**Comment by TimothyGu** [comment]
@RobLoach that is indeed a little ugly. Or maybe no floating like [Babel's](https://github.com/babel/babel)?

@tunnckoCore your design look a little weird since the name of the module is smaller than the tagline text

**Comment by TimothyGu** [comment]
@stoeffel THANKS!

**Comment by RobLoach** [comment]
Not sure about centered.
jstranscenter

**Comment by TimothyGu** [comment]
<h1 align=center>Looks absolutely wonderful!</p>

Two nits: I'm not so sure about using HTML 4-style `align` attr, and I'd also center the badges. Other than that, I'd say this PR is good to go. An SVG version would be a plus, but I don't think that's a blocker in any means.

@stoeffel just to be sure this logo is under MIT License right?

**Comment by stoeffel** [comment]
> just to be sure this logo is under MIT License right?

Yop It is.

**Comment by stoeffel** [comment]
:+1: for the centered one.

**Comment by RobLoach** [comment]
> I'm not so sure about using HTML 4-style align attr

GitHub's markdown parser seems to remove `style="text-align:center"`, along with some other methods of achieving this. If you have any ideas, we could them out.

> and I'd also center the badges

Done.

**Comment by RobLoach** [comment]
It passes, I promise.

**Comment by stoeffel** [comment]
@RobLoach Yop, github still doesn't support svg in markdown.

**Comment by TimothyGu** [comment]
Alright just merged this. Thanks everyone!

**Pull request merged**
