### PR TITLE
render: Prefer locals over options if both are present

### LINKED ISSUE #18: Problems with `.renderFileAsync`
I dont know why, but for some reason it fails to populate template with given locals in some template engines like handlebars and I guess other was toffee. [check this](https://github.com/tunnckoCore/jstransformer-handlebars/blob/master/test/index.js#L82) and [this](https://github.com/jstransformers/jstransformer-toffee/blob/master/test/index.js#L83), its not logical to fail, because other render* methods works correctly.

For that reason Im so strong with my position to use `jstransformer` for testing it helps to find bugs like this, have more useful use cases which in other hand in one point is useful as examples.

### PR DESCRIPTION
**Pull request by TimothyGu**
Fixes #18.

### CODE REVIEW

**Comment by tunnckoCore** [comment]
I thought its absolutely the same, but will try it.
because when you call the method like `method('', {}, locals)` and in core of jstransformer is `options || locals` it will choose locals, because options is empty object.

**Comment by tunnckoCore** [comment]
and yes, as I guess, result is the same.
```
{ body: '<p>Hello, my name is .</p>', dependencies: [] }
```

**Comment by TimothyGu** [comment]
> because when you call the method like `method('', {}, locals)` and in core of jstransformer is options || locals it will choose locals, because options is empty object.

```js
    !!({})
//> true
    var options = {}
//> undefined
    options || { locals: true }
//> {}
```

Please have some knowledge of JavaScript before replying.

> and yes, as I guess, result is the same.
> ```js
{ body: '<p>Hello, my name is .</p>', dependencies: [] }
```

Please show your entire test script. I believe this is an error on your end.

**Comment by tunnckoCore** [comment]
I mention them in #18  [this](https://github.com/tunnckoCore/jstransformer-handlebars/blob/master/test/index.js#L82) and [this](https://github.com/jstransformers/jstransformer-toffee/blob/master/test/index.js#L83)

**Comment by tunnckoCore** [comment]
omg, I should sleep more, lol. it isn't published, how i expect to work, lol

Hm. It is strange that the problem is only on `renderFileAsync`. With falsey value it works as expected, yes. But other methods works both with `{}` and with falsey value.
If you try to set options to `null` only for `renderFileAsync` and `{}` for other render methods all works correctly - this is strange diff.

**Pull request merged**
