### PR TITLE
Fix: added new logo

### LINKED ISSUE #221: trademark/copyright issue on logo
The 'autobot' portion of the logo used is a trademark registered to Hasbro, Inc. (US: [76673705](http://tarr.uspto.gov/servlet/tarr?regser=serial&entry=76673705http://tarr.uspto.gov/servlet/tarr?regser=serial&entry=76673705)), to avoid potential litigation/trademark issues, I feel as if the logo should be changed: as the [MIT License](https://opensource.org/licenses/MIT) implies copyright on the respected image, which may be a potential violation.

I personally don't think it's the best idea to have a giant, well-funded legal team descend unto this project, so I'd say "better safe than sorry".

### PR DESCRIPTION
**Pull request by AtlasJan**
Fix #221

### CODE REVIEW

**Comment by RobLoach** [comment]
Love it!

**Comment by AtlasJan** [comment]
New commit tweaked a few things, and brought it in compliance with the semantic pull request

**Comment by AtlasJan** [comment]
Could someone fix the README for me? That'd be appreciated.

**Comment by RobLoach** [comment]
> Could someone fix the README for me?

https://github.com/jstransformers/jstransformer/pull/226

**Pull request merged**
